FileVersion = 1
Projects = {gui = {Path = "."}, LybLog = "*", raylib-beef = "*", BeefBrand = "*", gon-beef = "*"}

[Workspace]
StartupProject = "gui"
PreprocessorMacros = ["LOG_DEBUG"]

[Configs.Debug.Win64]
ConfigSelections = {raylib-beef = {Config = "DebugStatic"}}

[Configs.Release.Win64]
ConfigSelections = {raylib-beef = {Config = "ReleaseStatic"}}
