FileVersion = 1
Projects = {sui = {Path = "."}, LybLog = "*", raylib-beef = "*"}

[Workspace]
StartupProject = "sui"
PreprocessorMacros = ["LOG_DEBUG"]

[Configs.Debug.Win64]
ConfigSelections = {raylib-beef = {Config = "DebugStatic"}}

[Configs.Release.Win64]
ConfigSelections = {raylib-beef = {Config = "ReleaseStatic"}}
