FileVersion = 1
Dependencies = {corlib = "*", LybLog = "*", raylib-beef = "*"}

[Project]
Name = "sui"
StartupObject = "sui.Program"

[Configs.Debug.Win64]
CLibType = "Dynamic"
BeefLibType = "Static"

[Configs.Release.Win64]
BuildKind = "StaticLib"
CLibType = "Dynamic"
