FileVersion = 1
Dependencies = {corlib = "*", LybLog = "*", raylib-beef = "*", BeefBrand = "*", gon-beef = "*"}

[Project]
Name = "gui"
StartupObject = "gui.Program"

[Configs.Debug.Win64]
CLibType = "Dynamic"
BeefLibType = "Static"

[Configs.Release.Win64]
CLibType = "Dynamic"
